# Generated by Django 4.0.4 on 2022-06-21 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blogappuser_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('parent_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'app_blogcategories',
            },
        ),
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 37, 41, 906741)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 37, 41, 907740)),
        ),
    ]
