# Generated by Django 4.0.4 on 2022-10-24 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blogcategory_alter_blogappuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 44, 36, 676661)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 44, 36, 677658)),
        ),
    ]
