# Generated by Django 4.0.4 on 2022-10-24 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blogappuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 46, 34, 901471)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 46, 34, 902469)),
        ),
    ]
